add middleware - check userAdmin
alkemyTech/OT200-Server pull request #10
Opened 2022-05-24 02:57 UTC by gtiavo

### Middleware para verificar usuario administrador

COMO usuario administrador
QUIERO restringir el acceso a cierto contenido
PARA mantener los datos protegidos 

Criterios de aceptación:
Deberá verificar el campo roleId, y permitir continuar si el usuario tiene rol correspondiente a administrador

2022-05-27 00:56 UTC, maxxCeballos requested changes

2022-05-27 00:56 UTC, maxxCeballos commented on middleware/checkAdmin.js
> +      const rolUser = req.rolId;
lo mas probable es que aca no venga el `rolId` directamente sobre el objeto `req` pueden utilizar algo como `req.user.rolId` ya que rolId es una property de user y no de req.

2022-05-27 00:56 UTC, maxxCeballos commented on middleware/checkAdmin.js
> +      const rolAdmin = await db.Role.findOne({where: { name: 'Admin'} });
No hacer llamadas a la base de datos desde un middleware, hacer la query bajo una funcion en la capa de Datos y llamar desde aca a la funcion que se encuentra en la capa de datos

2022-05-28 15:15 UTC, gtiavo commented on middleware/checkAdmin.js
> +      const rolUser = req.rolId;
perfecto, ya hice la modificación.

2022-05-28 15:16 UTC, gtiavo commented on middleware/checkAdmin.js
> +      const rolAdmin = await db.Role.findOne({where: { name: 'Admin'} });
modificado y pusheado.

2022-05-30 23:37 UTC, maxxCeballos approved these changes

2022-05-31 01:07 UTC, merged