Ot200 24 endpoint registro de usuarios
alkemyTech/OT200-Server pull request #11
Opened 2022-05-24 03:02 UTC by gamcode98

### Endpoint registro de Usuarios
**Descripción**
COMO usuario
QUIERO registrarme en el sistema
PARA ser parte del mismo

**Criterios de aceptación:**

- Se debe hacer una petición POST /auth/register 
- El endpoint deberá validar los campos Nombre, Apellido, Email, Contraseña. 
- La contraseña debe ser encriptada. 
- Deberá devolver como respuesta el usuario generado.

1. Validar
2. Encriptar contraseña
3. Almacenar en base de datos

Para validar utilizaremos express validator [https://express-validator.github.io/docs/](https://express-validator.github.io/docs/)

2022-05-27 01:07 UTC, maxxCeballos requested changes

2022-05-27 01:07 UTC, maxxCeballos commented on app.js
> +const authRouter = require("./routes/auth");
este es el unico cambio que deberia estar en el archivo

2022-05-27 01:07 UTC, maxxCeballos commented on controllers/auth.controller.js
> +        });
Las llamadas a la base de datos van por fuera del controller, en una capa de datos

2022-05-28 01:10 UTC, gamcode98 commented on controllers/auth.controller.js
> +        });
La llamada de base de datos es en una carpeta externa? o en el mismo controller pero en una función y de ahí llamar a dicha función?

2022-05-28 02:04 UTC, closed without merging