Ot200 22/modelo migracion controlador base de members
alkemyTech/OT200-Server pull request #12
Opened 2022-05-24 14:03 UTC by gtiavo

### Crear modelo, migración y controlador base de Members
Descripción

Campos:
id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
facebookUrl: VARCHAR NULLABLE
instagramUrl: VARCHAR NULLABLE
linkedinUrl: VARCHAR NULLABLE
image: VARCHAR NOT NULL

2022-05-24 14:05 UTC, gtiavo commented
"_NR" en commit: No Relevante

2022-05-27 00:38 UTC, maxxCeballos requested changes

2022-05-27 00:38 UTC, maxxCeballos commented on models/member.js
> +    modelName: 'Member',
falta agregar timestamp y softdelete

2022-05-30 23:32 UTC, maxxCeballos approved these changes

2022-05-31 01:07 UTC, merged