OT200-32-anadir-logica-de-jwt
alkemyTech/OT200-Server pull request #13
Opened 2022-05-27 06:27 UTC by soymariomtz

**Añadir lógica de JWT**

Criterios de aceptación:

- Cuando el usuario se autentica, el servidor deberá generar un JSON Web Token con los datos del usuario, y devolver el mismo en la respuesta.
- Para validar que el usuario está autenticado, el servidor deberá desencriptar este token, obteniéndolo del encabezado Authorization de la petición recibida.

2022-05-27 06:34 UTC, soymariomtz commented
No se bien donde deberia aplicar la logica de descencriptar token.

2022-05-30 23:57 UTC, maxxCeballos requested changes

2022-05-30 23:57 UTC, maxxCeballos commented on routes/auth.js
> +router.post('/login', userController.login)
esto esta en el PR de endpoint de autenticacion, no tiene que estar aca.

2022-05-30 23:57 UTC, maxxCeballos commented on services/auth.js
> +module.exports = findUser;
esto esta en el PR de endpoint de autenticacion, no tiene que estar aca.

2022-05-30 23:57 UTC, maxxCeballos commented on controllers/userController.js
> +            }
el `else` no es necesario, ya que si el password es invalido hace un return y esto no se ejecuta.

2022-05-30 23:57 UTC, maxxCeballos commented on middleware/userToken.js
> +}
esto esta fuera del alcance del ticket.

2022-06-01 23:42 UTC, maxxCeballos requested changes

2022-06-01 23:49 UTC, maxxCeballos approved these changes

2022-06-02 02:14 UTC, merged