Se agrega endpoint listado categorias
alkemyTech/OT200-Server pull request #18
Opened 2022-05-29 13:44 UTC by ldato

COMO usuario administrador
QUIERO listar las Categorías
PARA poder gestionar las Categorías

Criterios de aceptación:
GET a /categories. Devolverá el listado de categories. Solamente devolverá el campo name de las mismas

Aclaro que me faltan, ya que no tengo disponible en la rama, los middelware de autenticación con token y autorización del admin, que en este caso, importe como string para poder avanzar.

2022-06-05 23:39 UTC, maxxCeballos requested changes

2022-06-05 23:39 UTC, maxxCeballos commented on controllers/categories.js
> +//HAGO EL CONTROLLER PARA PODER AVANZAR.
Sacar los comentarios, cualquier duda que se pueda generar, aclarar en la descripción del PR, pero no dejarlo en codigo.

2022-06-05 23:39 UTC, maxxCeballos commented on routes/categories.js
> +const checkAdmin = "Se importara el middleware para verificar si el uusuario es Admin";
estan para importar

2022-06-05 23:39 UTC, maxxCeballos commented on routes/categories.js
> +router.get("/", verifyToken, checkAdmin(req.user.id), findAll);
checkAdmin trabaja con los parametros req, res que recibe, porque se le pasa el userId?

2022-06-05 23:39 UTC, maxxCeballos commented on controllers/categories.js
> +    const categories = await findAll();
await solo se puede utilizar dentro de una funcion async.

2022-06-05 23:39 UTC, maxxCeballos commented on routes/categories.js
> +//DEBO REQUERIR MODELO Y CONTROLLER DE CATEGORIAS
sacar estos comentarios, tratar de evitar subirlos al repositorio.

2022-06-05 23:39 UTC, maxxCeballos commented on controllers/categories.js
> +    res.json(categories);
Que pasa si sucede un error? no se esta catcheando, devolver status code y mensaje apropiado ante un error.

2022-06-06 22:34 UTC, ldato commented on routes/categories.js
> +const checkAdmin = "Se importara el middleware para verificar si el uusuario es Admin";
Hice un merge con main y aparecieron los archivos, se realizo la importación.

2022-06-06 22:35 UTC, ldato commented on routes/categories.js
> +router.get("/", verifyToken, checkAdmin(req.user.id), findAll);
Pensé que debía pasarle el objeto req que viene de verifyToken, se corrigió el endpoint

2022-06-06 22:35 UTC, ldato commented on routes/categories.js
> +//DEBO REQUERIR MODELO Y CONTROLLER DE CATEGORIAS
Se eliminaron los comentarios.

2022-06-06 22:35 UTC, ldato commented on controllers/categories.js
> +    res.json(categories);
Realice un try/catch para capturar el error.

2022-06-08 03:19 UTC, maxxCeballos approved these changes

2022-06-08 03:27 UTC, merged