Ot200 43/endpoint creación categorías
alkemyTech/OT200-Server pull request #21
Opened 2022-05-31 22:44 UTC by gtiavo

## Endpoint Creación Categorías
#### Descripción

COMO usuario administrador
QUIERO agregar una categoría nueva al sistema
PARA categorizar las Novedades

Criterios de aceptación:
POST /categories - Deberá validar que se envíe el campo name, y el mismo sea un string

2022-06-01 23:55 UTC, maxxCeballos requested changes

2022-06-01 23:55 UTC, maxxCeballos commented on app.js
> +app.use('/categories', require('./routes/categories'));
el require hacerlo arriba del archivo donde se importan todos los modulos.

2022-06-01 23:55 UTC, maxxCeballos commented on routes/categories.js
> +]),
esto hacerlo en una funcion aparte, en un archivo de validations

2022-06-01 23:55 UTC, maxxCeballos commented on controllers/categories.js
> +      res.json({ msg:'Crear categoria', name})
falta persistir la categoria en la base de datos.

2022-06-05 23:51 UTC, maxxCeballos requested changes

2022-06-05 23:51 UTC, maxxCeballos commented on routes/categories.js
> +
falta validar que sea un usuario administrador el que ejecuta la accion.

2022-06-05 23:51 UTC, maxxCeballos commented on helpers/index.js
> +const checkFields = require('./checkFields');
utilizar un nombre menos genérico, checkCategoriesFields o algo por el estilo.

2022-06-05 23:51 UTC, maxxCeballos commented on controllers/categories.js
> +//Metodo POST/ TODO:crear una nueva categoria en DB
Evitar puishear estos comentarios. Los nombres de las variables y funciones tienen que poder transmitir lo que se esta haciendo.

2022-06-05 23:51 UTC, maxxCeballos commented on services/category.js
> +    //Se crea la categoria
evitar estos comentarios, se entiende lo que se esta haciendo. Al nombre de la funcion si le pondria createCategory para ser mas especifico sobre lo que se esta creando.

2022-06-05 23:51 UTC, maxxCeballos commented on controllers/categories.js
> +      res.status(200).json({ msg:'ok', categoria});
que sucede si hay un error? Se debe catchear y deolver un status code apropiado

2022-06-06 14:21 UTC, gtiavo commented on helpers/index.js
> +const checkFields = require('./checkFields');
Mi idea era que sea un archivo genérico, ahí quería alojar los campos a validar de cualquier endpoint y guardarlos en variables con nombres específicos en relación al modelo de sequelize. Si es una mala practica lo modifico.

2022-06-09 00:59 UTC, maxxCeballos approved these changes

2022-06-09 01:45 UTC, merged