Ot200 59 endpoint creacion slides
alkemyTech/OT200-Server pull request #24
Opened 2022-06-01 04:17 UTC by ambergesio

COMO usuario administrador
QUIERO poder crear Slides 
PARA agregar más información al comienzo de la pagina
Criterios de aceptación: 
Se debe hacer una peticion POST /Slides 
Recibirá la imágen a almacenar en base 64. La misma deberá ser decodeada y almacenada en Amazon S3 (almacenamiento en /public/slides con multer).
En el caso de no recibir el campo order, deberá establecer el mismo como el último en base a los existentes

2022-06-02 02:22 UTC, maxxCeballos requested changes

2022-06-02 02:22 UTC, maxxCeballos commented on services/slide.service.js
> +  }
Este try/catch es innecesario, porque no se hace nada con el error, se catchea pero se vuelve a lanzar, es lo mismo que no catchearlo.

2022-06-02 02:22 UTC, maxxCeballos commented on services/slide.service.js
> +  }
Mismo caso anterior con el try/catch

2022-06-02 02:22 UTC, maxxCeballos commented on controllers/slides.controller.js
> +  };
esto lo pondria dentro del try

2022-06-02 02:22 UTC, maxxCeballos commented on controllers/slides.controller.js
> +    res.status(200).json({error: false, data: newSlide, message: "creaste un nuevo slide"});
cuando se crea un recurso el status code apropiado es 201

2022-06-02 03:48 UTC, ambergesio commented on controllers/slides.controller.js
> +  };
Incluído dentro del try

2022-06-02 03:49 UTC, ambergesio commented on controllers/slides.controller.js
> +    res.status(200).json({error: false, data: newSlide, message: "creaste un nuevo slide"});
Status cambiado a 201

2022-06-02 13:29 UTC, ambergesio commented on services/slide.service.js
> +  }
Modificado

2022-06-03 14:21 UTC, maxxCeballos approved these changes

2022-06-03 15:48 UTC, merged