Ot200 17 crear modelo migracion y controlador base de users
alkemyTech/OT200-Server pull request #3
Opened 2022-05-23 21:15 UTC by ambergesio

Campos:
id: INTEGER NOT NULL AUTO_INCREMENT
firstName: VARCHAR NOT NULL
lastName: VARCHAR NOT NULL
email: VARCHAR UNIQUE NOT NULL
password: VARCHAR NOT NULL
photo: VARCHAR NULLABLE
roleId: Clave foranea hacia ID de Role
timestamps y softDeletes

2022-05-24 00:59 UTC, maxxCeballos requested changes

2022-05-24 00:59 UTC, maxxCeballos commented on controllers/roles.controller.js
> +}
Esto esta fuera de scope, no se pide en el ticket.

2022-05-24 00:59 UTC, maxxCeballos commented on controllers/users.controller.js
> +}
Esto esta fuera de scope, no se pide en el ticket.

2022-05-24 00:59 UTC, maxxCeballos commented on models/role.js
> +    timestamps: true,
Esto pertenece al ticket de Rol, no tiene que ir en este PR

2022-05-24 13:08 UTC, ambergesio commented on controllers/roles.controller.js
> +}
Borré el archivo

2022-05-27 00:14 UTC, maxxCeballos approved these changes

2022-05-27 00:36 UTC, merged