Se agrega ruta, service y controller para  listar comentarios con los…
alkemyTech/OT200-Server pull request #34
Opened 2022-06-05 15:28 UTC by ldato

… fixes comentados en cada archivo

2022-06-06 02:06 UTC, maxxCeballos requested changes

2022-06-06 02:06 UTC, maxxCeballos commented on routes/comments.js
> +//Se comentan ambos middlewares para realizar prueba de ruta.
sacar estos comentarios

2022-06-06 02:06 UTC, maxxCeballos commented on routes/comments.js
> +// checkAdmin,
estan disponibles estos middlewares, siguen sin funcionar?

2022-06-06 02:06 UTC, maxxCeballos commented on models/news.js
> +      New.hasOne(models.Categories, {//SE CAMBIA CATEGORY POR CATEGORIES POR QUE TIRA ERRROR CON models.Category
Esto ya lo resolvio quien correspondia, volver a dejar como estaba, y en caso de hacer algun arreglo evitar hacer las aclaraciones en el codigo, hacerlo en la descripcion del PR.

2022-06-06 02:06 UTC, maxxCeballos commented on migrations/20220521171147-create-activity.js
> +      },
evitar estos cambios innecesarios, hacen mas lenta la revision.

2022-06-06 02:06 UTC, maxxCeballos commented on models/slide.js
> +      // });
Si bien esta bien comentar las lineas que generan error, unas vez hechas las pruebas hay que volver a dejar el codigo como estaba y avisar para que el responsable de esa tarea lo arregle.

2022-06-06 02:06 UTC, maxxCeballos commented on services/comment.js
> +    //Pero el mismo probrado con activities funciona correctamente.
Sacar estos comentarios, las aclaraciones hacerlas en la descripcion del PR.

2022-06-06 02:06 UTC, maxxCeballos commented on controllers/comment.controller.js
> +    res.status(201).json(comments);
El status code apropiado para un get es un 200. El status 201 se retorna cuando creamos un recurso.

2022-06-06 02:06 UTC, maxxCeballos commented on controllers/comment.controller.js
> +    res.status(201).json(comments);
Si ocurre un error en la ejecucion de la consulta a la base de datos no se esta manejando, manejar el error y devolver un status 500.

2022-06-06 22:57 UTC, ldato commented on models/news.js
> +      New.hasOne(models.Categories, {//SE CAMBIA CATEGORY POR CATEGORIES POR QUE TIRA ERRROR CON models.Category
se vuelve a models.Category

2022-06-10 16:17 UTC, maxxCeballos approved these changes

2022-06-13 21:35 UTC, merged