middleware checkOwnership added
alkemyTech/OT200-Server pull request #36
Opened 2022-06-06 02:14 UTC by gamcode98

### Middleware de Ownership
COMO usuario
QUIERO acceder únicamente a las secciones permitidas para mi rol
PARA completar ciertas acciones

Criterios de aceptación:
Se utilizará para proteger endpoints que son solo para el usuario actual. Deberá verificar el parámetro id y compararlo con el ID del usuario enviado en el token JWT, caso contrario, devolver error 403. Sin embargo, si el usuario que es enviado en el token es administrador, si le permitirá continuar

2022-06-06 02:17 UTC, gamcode98 commented
Para usar este middleware se requiere el uso previo del middleware **verifyToken** quien envia info del token (id, roleId)

2022-06-06 02:39 UTC, gamcode98 commented
Ejemplo: 

`//routes/users.js

router.put(
  "/:id",
  verifyToken,
  checkOwnership,
  update
)`

2022-06-08 01:11 UTC, maxxCeballos requested changes

2022-06-08 01:11 UTC, maxxCeballos commented on middleware/checkOwnership.js
> +    if (Number(id) === tokenId || tokenId === 1) return next();
En el ticket dice tambien: `Sin embargo, si el usuario que es enviado en el token es administrador, si le permitirá continuar`

2022-06-08 01:11 UTC, maxxCeballos commented on middleware/checkOwnership.js
> +    return res.status(403).json({
Para este caso es mas apropiado status code 401

2022-06-08 01:51 UTC, gamcode98 commented on middleware/checkOwnership.js
> +    return res.status(403).json({
Okey. El ticket me sugirió ese status 403 por eso lo puse

2022-06-08 01:54 UTC, gamcode98 commented on middleware/checkOwnership.js
> +    if (Number(id) === tokenId || tokenId === 1) return next();
Si, y es que en el token viaja el roleId, y como el admin es roleId = 1

2022-06-08 22:12 UTC, gamcode98 commented on middleware/checkOwnership.js
> +    if (Number(id) === tokenId || tokenId === 1) return next();
Listo Maxi, ya realicé el cambio

2022-06-09 00:56 UTC, maxxCeballos approved these changes

2022-06-09 01:58 UTC, merged