endpoint delete member done
alkemyTech/OT200-Server pull request #37
Opened 2022-06-06 02:22 UTC by gamcode98

### Endpoint Eliminación Miembros

COMO usuario
QUIERO eliminar un miembro
PARA que no sea más parte de la Organización

Criterios de aceptación:
Criterios de aceptación:DELETE /members/:id - Deberá validar que el miembro existe y eliminarlo, caso contrario devolver un error

2022-06-08 01:08 UTC, maxxCeballos requested changes

2022-06-08 01:08 UTC, maxxCeballos commented on routes/members.js
> +  // verifyToken,
sigue sin funcionar esto?

2022-06-08 01:08 UTC, maxxCeballos commented on controllers/members.controller.js
> +        })
Mismo caso que se corrige en delete de categories

2022-06-08 01:08 UTC, maxxCeballos commented on services/member.js
> +}
Mismo caso que se corrige en delete de categories

2022-06-08 13:17 UTC, gamcode98 commented on routes/members.js
> +  // verifyToken,
Según yo, si. No funciona

2022-06-08 13:17 UTC, gamcode98 commented on controllers/members.controller.js
> +        })
Listo Maxi

2022-06-08 13:17 UTC, gamcode98 commented on services/member.js
> +}
Listo, también

2022-06-09 00:54 UTC, maxxCeballos approved these changes

2022-06-09 02:34 UTC, merged