OT200-26 Middleware para Usuarios autenticados
alkemyTech/OT200-Server pull request #4
Opened 2022-05-23 21:16 UTC by ldato

Middleware para Usuarios autenticados

Descripción

COMO usuario autenticado
QUIERO restringir el acceso a cierto contenido
PARA mantener los datos protegidos 

Criterios de aceptación:
Deberá chequear si la petición contiene el token correspondiente a un usuario, caso contrario deberá devolver un código de error 403 con un mensaje de error.

2022-05-24 01:11 UTC, maxxCeballos requested changes

2022-05-24 01:11 UTC, maxxCeballos commented on middleware/verifyToken.js
> +const secret = "AlkemyLab";//Esta variable debe ir en un archivo de configuración
utilizar archivo .env para las variables de entorno.

2022-05-24 01:11 UTC, maxxCeballos commented on middleware/verifyToken.js
> +            }
por que el try/catch para next()? puede producir un error la llamada? por otro lado, el else es innecesario, podes hacer:

```
if (error) {
  res.status(400).send({message: "Token invalido"});
}
next();
```

2022-05-24 01:11 UTC, maxxCeballos commented on middleware/verifyToken.js
> +            }
por que el try/catch para next()? puede producir un error la llamada? por otro lado, el else es innecesario, podes hacer:

```
if (error) {
  res.status(400).send({message: "Token invalido"});
}
next();
```

2022-05-27 00:51 UTC, maxxCeballos commented on middleware/verifyToken.js
> +            }
Esto sigue sin corregir

2022-05-27 00:51 UTC, maxxCeballos commented on middleware/verifyToken.js
> +            }
Otro tema, cuando haces el verify solo estas tomando del callback el error, pero si eso da bien, tenes que obtener el payload decodificado y guardarlo en el objeto `req` para poder obtenerlo en la proxima funcion que se invoca con `next()`

2022-05-27 17:22 UTC, ldato commented on middleware/verifyToken.js
> +            }
Se guarda user en objeto req, req.user

2022-05-27 17:22 UTC, ldato commented on middleware/verifyToken.js
> +const secret = "AlkemyLab";//Esta variable debe ir en un archivo de configuración
Se corrige secret desde .env

2022-05-30 23:31 UTC, maxxCeballos approved these changes

2022-05-31 01:06 UTC, merged