Ot200 48 endpoint actualizacion novedades
alkemyTech/OT200-Server pull request #40
Opened 2022-06-06 16:21 UTC by soymariomtz

COMO usuario administrador
QUIERO actualizar una novedad existente
PARA poder mantener a información actualizada

Criterios de aceptación:
PUT /news/:id - Deberá validar que la novedad exista en base al id enviado por parámetro. En el caso de que no exista devolver un error, caso contrario actualizar la novedad y devolver la misma con los datos actualizados

2022-06-08 00:54 UTC, maxxCeballos requested changes

2022-06-08 00:54 UTC, maxxCeballos commented on services/news.js
> +}
Esta funcion no tiene que estar en este PR. Cuando se van a agregar distintos features hay que salir siempre de la rama `main` . De esta manera no se revisa dos veces lo mismo.

2022-06-08 00:54 UTC, maxxCeballos commented on routes/news.js
> +// validatorHandler(newsFieldsValidation),
que paso con esto? no esta andando todavia?

2022-06-08 00:54 UTC, maxxCeballos commented on controllers/news.js
> +        }
Esto no es necesario, se puede utilizar la repuesta del update para saber si no se encontraba la novedad que queremos actualizar. En base a esa respuesta se puede devolver un 404.

2022-06-08 00:54 UTC, maxxCeballos commented on controllers/news.js
> +    }
es necesario 2 try/catch? con uno solo se puede lograr lo mismo.

2022-06-09 15:52 UTC, soymariomtz commented on routes/news.js
> +// validatorHandler(newsFieldsValidation),
esta en otro PR que todavía no esta aprobado, por eso lo deje comentado.

2022-06-15 02:17 UTC, maxxCeballos requested changes

2022-06-15 02:17 UTC, maxxCeballos commented on controllers/news.js
> +        }
Esto para que se hace?

2022-06-15 02:17 UTC, maxxCeballos commented on controllers/news.js
> +        }
Esto habia remarcado que no era necesario, se estan haciendo dos consultas a la base de datos, cuando se puede hacer solo en una, verificando el valor que viene en la respuesta del update del service. Leer documentacion de que devuelve `update` de sequelize.

2022-06-20 00:28 UTC, maxxCeballos approved these changes

2022-06-22 00:22 UTC, merged