Ot200 82 Endpoint Actualización Comentarios
alkemyTech/OT200-Server pull request #50
Opened 2022-06-09 22:26 UTC by Rsdjsp

COMO usuario
QUIERO actualizar un comentario propio
PARA mantener la información actualizada

Criterios de aceptación:
PUT /comments/:id - Deberá validar la existencia del comentario en base a su id. Solamente podrán editar un comentario el usuario que lo realizó o un administrador

2022-06-14 00:48 UTC, maxxCeballos requested changes

2022-06-14 00:48 UTC, maxxCeballos commented on routes/comments.js
> +router.put("/:id", verifyToken, validatorHandler(updateFields), verifyOwner, updateComment);
- Se probo esto?
- verifyOwner tiene que ir antes de validar los fields, es decir: router.put(path, verifyToken, verifyOwner, validator, update)
- Por otro lado, el middleware de Owner lo implementó Gabriel, por lo tanto hay que utilizar el que implementó él.

2022-06-14 00:48 UTC, maxxCeballos commented on middleware/validatecomments.js
> +module.exports = verifyOwner;
Sacar esto, utilizar el middleware de Ownership que implementó Gabriel.

2022-06-14 00:48 UTC, maxxCeballos commented on helpers/checkCommentsFields.js
> +    check('post_id', 'Please introduce a valid post_id').isEmpty(),
Aca estas validando que post_id este vació. Este parametro lo estas utilizando despues para hacer la consulta a la base de datos, por lo que se deberia validar que no sea vacio.

Por otro lado, si estas validando los mismos datos que en commentsFields, por qué no reutilizas los mismos?

2022-06-15 03:22 UTC, Rsdjsp commented on helpers/checkCommentsFields.js
> +    check('post_id', 'Please introduce a valid post_id').isEmpty(),
Hola Maxi como puedes ver no son las mismas validaciones que en commandfields ya que yo solo requiero como obligatorio el campo de user_id; no  son obligatorios en el update todos los campos.

2022-06-15 03:38 UTC, Rsdjsp commented on routes/comments.js
> +router.put("/:id", verifyToken, validatorHandler(updateFields), verifyOwner, updateComment);
El verify Owner tiene que ir después de validar los campos de la solicitud, ya que depende el campo user_id para validar el propietario del comentario, si invierto el orden se rompería la aplicación.

Por otro lado, al momento de la solicitud del tiquet no se había aprobado el middleware de Gabriel, por lo que no lo tengo disponible para usar en mi rama.

2022-06-20 01:03 UTC, maxxCeballos approved these changes

2022-06-22 22:24 UTC, merged