Ot200 84/endpoint listar comentarios en base a un post
alkemyTech/OT200-Server pull request #52
Opened 2022-06-11 13:51 UTC by gtiavo

## Endpoint para listar Comentarios en base a un post

### Descripción

COMO usuario
QUIERO visualizar los Comentarios de un post
PARA obtener la información organizada

Criterios de aceptación:
GET /posts/:id/comments - Devolverá todos los Comentarios pertenecientes a un post

2022-06-14 00:55 UTC, maxxCeballos requested changes

2022-06-14 00:55 UTC, maxxCeballos commented on controllers/comments.controller.js
> +    if( comments == '' ) return res.status(200).json({ error: false, message:'No se encontraron comentarios en este post', comments});
No hacer este tipo de validaciones. Si comments es un array, utilizar la propiedad de longitud y verificar que sea cero:

`if (comments.length === 0) {...}`

2022-06-14 01:09 UTC, gtiavo commented on controllers/comments.controller.js
> +    if( comments == '' ) return res.status(200).json({ error: false, message:'No se encontraron comentarios en este post', comments});
uhhh, es verdad... no lo tuve en cuenta. gracias maxi

2022-06-15 02:03 UTC, maxxCeballos approved these changes

2022-06-15 21:33 UTC, merged