Ot200 31 envio de mail de bienvenida
alkemyTech/OT200-Server pull request #61
Opened 2022-06-13 16:07 UTC by soymariomtz

COMO usuario
QUIERO ver un mail de bienvenida cuando me registro
PARA asegurarme que el registro ocurrió correctamente.

Criterios de aceptación:

- Utilizar el servicio de envío de emails y el template de bienvenida para enviar un email de forma programática cuando un usuario se registre, al email que proporcionó en su registro

2022-06-14 01:26 UTC, maxxCeballos requested changes

2022-06-14 01:26 UTC, maxxCeballos commented on controllers/auth.controller.js
> +            welcomeMail(subject, emailText, contactInfo, newUser.email, emailTitle)
subject, emailText y contactInfo de donde se sacan?

2022-06-14 01:26 UTC, maxxCeballos commented on services/sendMail.js
> +const welcomeMail = async ( email, subject) => {
Aca estas recibiendo 2 argumentos en la funcion y desde el controller estas enviando 5 parámetros, por qué esta diferencia?

2022-06-14 01:26 UTC, maxxCeballos commented on services/sendMail.js
> +      html: templateEmail,
templateEmail de donde sale?

2022-06-14 01:26 UTC, maxxCeballos commented on services/sendMail.js
> +      }
es necesario este try/catch solo para hacer un console.log?

2022-06-14 02:34 UTC, soymariomtz commented on services/sendMail.js
> +const welcomeMail = async ( email, subject) => {
Hice una parte en el PR del template y parte del envío en este PR, debería dejar unificado en un PR?

2022-06-20 00:24 UTC, maxxCeballos approved these changes

2022-06-21 23:45 UTC, merged