Ot200 85/agregar paginacion categorias
alkemyTech/OT200-Server pull request #63
Opened 2022-06-14 00:08 UTC by gtiavo

# Agregar paginación a Categorías

### Descripción

COMO usuario
QUIERO visualizar los resultados de Categorías paginados
PARA aumentar la velocidad de respuesta

Criterios de aceptación:
Cuando se realice la petición para listar, los resultados deberán paginarse de a 10. En la respuesta, se deberán mostrar los resultados y las urls para la página anterior y siguiente (si corresponden). La página actual se obtendrá del parámetro de query ?page

2022-06-20 00:40 UTC, maxxCeballos requested changes

2022-06-20 00:40 UTC, maxxCeballos commented on services/categories.js
> +    const { count, rows  } = await db.Categories.findAndCountAll({ offset: page, limit: limite });
Entender el atirbuto offest, no se esta utilizando bien.

2022-06-20 00:40 UTC, maxxCeballos commented on services/categories.js
> +    const previous = ( data - limite );
esta cuenta esta mal sacada.

2022-06-20 00:40 UTC, maxxCeballos commented on controllers/categories.js
> +const CategoriesList = async(req, res) => {
Se podria haber utilizado la funcion getAll que ya estaba implementada y paginar esa respuesta.

2022-06-20 01:14 UTC, gtiavo commented on controllers/categories.js
> +const CategoriesList = async(req, res) => {
si, lo pense. pero este controller  esta siendo usado por una ruta que requiere usuario administrador. y el ticket me pedia que sea un usuario cualquiera. no sabia si era buena practica usar el mismo controlador en un mismo archivo de rutas

2022-06-22 22:19 UTC, gtiavo commented on services/categories.js
> +    const { count, rows  } = await db.Categories.findAndCountAll({ offset: page, limit: limite });
si, tenia un concepto erróneo de como se realizaba la paginación. Estuve revisando el código que hizo Gabi y ahí caí.

2022-06-23 00:44 UTC, maxxCeballos approved these changes

2022-06-24 22:18 UTC, maxxCeballos approved these changes

2022-06-24 22:19 UTC, merged