Ot200 77 Crear seed de Usuarios
alkemyTech/OT200-Server pull request #71
Opened 2022-06-17 15:53 UTC by Rsdjsp

COMO usuario administrador
QUIERO visualizar datos de prueba
PARA poder testear funcionalidades en la web.

Criterios de aceptación:
Crear un seeder para popular la base de datos con Usuarios para realizar pruebas. 10 Usuarios estándar y 10 regulares. Posteriormente, agregar los datos de los mismos en el README.md para permitir que los otros Miembros puedan utilizarlos

![image](https://user-images.githubusercontent.com/93556117/174333586-1fe08c24-bb1b-4be2-bd4d-36c1522f541f.png)

2022-06-20 00:51 UTC, maxxCeballos requested changes

2022-06-20 00:51 UTC, maxxCeballos commented on test.js
> +console.log(newUsers);
Sacar esto, no es la manera de hacer test, y tampoco se solicita en el ticket.

2022-06-21 23:06 UTC, Rsdjsp commented on test.js
> +console.log(newUsers);
Maxi en la ultima reunion me dijiste que tenia que encriptar el password, osea que dejo la contreseña de los usuarios sin encriptar?

2022-06-23 02:49 UTC, maxxCeballos requested changes

2022-06-23 02:49 UTC, maxxCeballos commented on models/user.js
> -  };
Por que se saca esto?

2022-06-23 02:53 UTC, Rsdjsp commented on models/user.js
> -  };
porque según tengo entendido Abel lo hizo antes de que se crearan los enpoints de autenticación, entonces como no se podía encriptar la contraseña la eliminaba, pero ahora que ya existe la encriptación no veo necesario remover el password del usuario

2022-06-28 01:29 UTC, merged