OT200-25-endpoint-de-autenticacion  y  OT200-32-anadir-logica-de-jwt
alkemyTech/OT200-Server pull request #8
Opened 2022-05-23 23:46 UTC by soymariomtz

**Endpoint de autenticación**

Criterios de aceptación:
- Se debe hacer una petición de tipo POST /auth/login 
- Deberá validarse el envío de los campos email y password en la petición, y desencriptar la contraseña para autenticarse

1. Validar email y password en petición 
2. Verificar si existe usuario con el email solicitado
3. Si existe, comparar contraseña encriptada con contraseña enviada en petición
4. Devolver al usuario en el caso de que exista y la contraseña sea válida, en el caso de que ocurra un error, devolver {ok: false}

**Añadir lógica de JWT**

Criterios de aceptación:
- Cuando el usuario se autentica, el servidor deberá generar un JSON Web Token con los datos del usuario, y devolver el mismo en la respuesta.
- Para validar que el usuario está autenticado, el servidor deberá desencriptar este token, obteniéndolo del encabezado Authorization de la petición recibida.

2022-05-27 00:58 UTC, maxxCeballos commented
Mario, los tickets tienen que ir en branchs separadas.

2022-05-27 01:14 UTC, maxxCeballos requested changes

2022-05-27 01:14 UTC, maxxCeballos commented on routes/auth.js
> +router.post('/login',verifyToken, generateToken, validLogin)
en este punto el usuario todavia no dispone del token, el token se devuelve despues de autenticarse, por lo tanto la verificacion y la generacion no van aca

2022-05-27 01:14 UTC, maxxCeballos commented on middleware/validLogin.js
> +    body('password').notEmpty().withMessage('Obligatorio').isLength({min:8}).withMessage('La contraseña debe tener al menos 8 caracteres.')
en un middle solo se debe validar que se envie el email y password, lo demas va todo en un controller y la consulta a la base de datos va en la capa de datos.

2022-05-27 01:14 UTC, maxxCeballos commented on middleware/userToken.js
> +}
esta logica no se solicita en el ticket

2022-05-27 01:14 UTC, maxxCeballos commented on middleware/userToken.js
> +}
esta funcion se tiene que llamar despues de validar que el usuario y password es correcto para generar el token y agregarlo como respuesta de login.

2022-05-27 04:45 UTC, soymariomtz commented
> Mario, los tickets tienen que ir en branchs separadas.

Ok, hice los cambios, en esta rama deje el Endpoint Autenticación y cree otra con la logica de JWT.

2022-05-27 06:30 UTC, soymariomtz commented on middleware/userToken.js
> +}
Lo pase a la rama correspondiente.

2022-05-27 06:32 UTC, soymariomtz commented on middleware/userToken.js
> +}
Lo pase a la rama correspondiente del ticket.

2022-05-27 22:54 UTC, soymariomtz commented on middleware/validLogin.js
> +]
Con lo que habías recomendado, debería poner la validación en routes?

2022-05-30 23:49 UTC, maxxCeballos requested changes

2022-05-30 23:49 UTC, maxxCeballos commented on app.js
> +const authRouter = require('./routes/users');
Esta ruta esta andando? se probo antes de subir? estas importando el router desde `routes/users` no `routes/auth`

2022-05-30 23:49 UTC, maxxCeballos commented on controllers/userController.js
> +        }
Esto lo pondria en el middle de validacion

2022-05-30 23:49 UTC, maxxCeballos commented on middleware/validLogin.js
> +]
No, esta bien aca me parece. En el controller te marque algo que si pondria aca, ya que tiene mas que ver con esto que con la logica que queremos desarrollar para el negocio en si.

2022-05-30 23:49 UTC, maxxCeballos commented on controllers/userController.js
> +            if(!findUser)res.status(404).json({message: 'Usuario no encontrado', ok: false});
Esto se probo que este funcionando? `findUser` es una funcion en el service y no se invoca en ningun momento

2022-06-01 23:50 UTC, maxxCeballos requested changes

2022-06-01 23:50 UTC, maxxCeballos commented on services/auth.js
> +const findUser = async (req, res) => {
Se probo esto? desde el controller estas llamando la funcion con el parametro email, y aca estas recibiendo dos argumentos.

2022-06-01 23:50 UTC, maxxCeballos commented on controllers/users.controller.js
> +            res.status(200).json({message: 'Login exitoso', user: user});
en la respuesta hay que devolver el token con el usuario dentro del token, tenes que llamar a la funcion que generaste en el otro ticket, y pasarle el usuario, y lo que retorna la funcion es lo que tenes que devolver en esta respuesta.

2022-06-05 22:51 UTC, maxxCeballos requested changes

2022-06-05 22:51 UTC, maxxCeballos commented on controllers/users.controller.js
> +                return res.status(400).json({message: 'Usuario no encontrado', ok: false});
Si no se encuentra el usuario es un 404.

2022-06-05 22:51 UTC, maxxCeballos commented on controllers/users.controller.js
> +            const user = findUser(email);
La funcion se invoca con un parametro, desde el service la funcion no recibe ningun parametro.

2022-06-05 22:51 UTC, maxxCeballos commented on services/auth.js
> +    const user = await db.User.findOne();
que usuario se busca aca si no se le pasa ningun dato de busqueda a la funcion? cualquier usuario?

2022-06-05 22:51 UTC, maxxCeballos commented on controllers/users.controller.js
> +    login: (req, res) => {
Esta funcion tiene que ir en el controller de auth.

2022-06-08 03:16 UTC, maxxCeballos approved these changes

2022-06-08 03:26 UTC, merged